const formstates = [
    {playerform:{
        name:{
            value:"",
            isValid:false
        },
        prename:{
            value:"",
            isValid:false
        },
        age:{
            value:"",
            isValid:false
        },
        image:{
            value:null,
            isValid:false
        },
        position:{
            value:"",
            isValid:false
        },
        number:{
            value:"",
            isValid:false
        },
        team:{
            value:"",
            isValid:false
        }
    }},
    {teamform:{
        name:{
            value:"",
            isValid:false
        },
        status:{
            value:"",
            isValid:false
        },
        image:{
            value:null,
            isValid:false
        },
        desc:{
            value:"",
            isValid:false
        },
        gender:{
            value:"",
            isValid:false
        },
        league:{
            value:"",
            isValid:false
        },
        insta:{
            value:"",
            isValid:false
        },
        fb:{
            value:"",
            isValid:false
        },
        trainers:{
            value:[],
            isValid: true
        },
        players:{
            value:[],
            isValid:true
        },
        trainings:{
            value:[],
            isValid:true
        }
    }},
    {trainerform:{
        name:{
            value:"",
            isValid:false
        },
        tel:{
            value:"",
            isValid:false
        },
        image:{
            value:null,
            isValid:false
        },
        email:{
            value:"",
            isValid:false
        },
        team:{
            value:"",
            isValid:false
        }
    }},
    {trainingsform:{
        start:{
            value:"",
            isValid:false
        },
        end:{
            value:"",
            isValid:false
        },
        day:{
            value:"",
            isValid:false
        },
        location:{
            value:"",
            isValid:false
        },
        link:{
            value:"",
            isValid:false
        },
        team:{
            value:"",
            isValid:false
        }
    }},
    {datesform:{
        title:{
            value:"",
            isValid:false
        }, 
        date:{
            value:"",
            isValid:false
        },
        category:{
            value:"",
            isValid:false
        }
}},
{leadsform:{
    name:{
        value:"",
        isValid:false
    },
    prename:{
        value:"",
        isValid:false
    },
    tel:{
        value:"",
        isValid:false
    },
    image:{
        value:null,
        isValid:false
    },
    category:{
        value:"",
        isValid:false
    },
    email:{
        value:"",
        isValid:false
    },
    comment:{
        value:"",
        isValid:false
    }
}

},
{sponsorsform:{
    name:{
        value:"",
        isValid:false
    },
   
    link:{
        value:"",
        isValid:false
    },
    image:{
        value:null,
        isValid:false
    },
    category:{
        value:"",
        isValid:false
    }
}}

];

export default formstates;